apiVersion: v1
kind: LimitRange
metadata:
  name: {{ required "name required" .Values.name }}
  namespace: {{ required "name required" .Values.namespace }}
  labels: {{- include "ffc-helm-library.labels" . | nindent 4 }}
spec:
  limits:
  - type: Container
    default:
      cpu: {{ required "default limit cpu required" .Values.limitRange.defaultLimitCpu }}
      memory: {{ required "default limit memory required" .Values.limitRange.defaultLimitMemory }}
    defaultRequest:
      cpu: {{ required "default request cpu required" .Values.limitRange.defaultRequestCpu }}
      memory: {{ required "default request memory required" .Values.limitRange.defaultRequestMemory }}
