apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ required "name required" .Values.name }}
  namespace: {{ required "name required" .Values.namespace }}
  labels: {{- include "ffc-helm-library.labels" . | nindent 4 }}
spec:
  hard:
    cpu: {{ required "request cpu required" .Values.resourceQuota.requestCpu }}
    memory: {{ required "request memory required" .Values.resourceQuota.requestMemory }}
