name: ffc-demo
namespace: ffc-demo
workstream: ffc-demo
environment: production

labels:
  instance:
  version: 1.0.0
  component: configuration

resourceQuota:
  requestCpu: 2000m
  requestMemory: 1Gi
